controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

app_sales:
    path: /sales
    controller: App\Controller\SalesController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_category_create:
    path: '/category/create'
    controller: App\Controller\CategoryController::create

app_category_list:
    path: '/category'
    controller: App\Controller\CategoryController::index

app_category_edit:
    path: '/category/{id}/edit'
    controller: App\Controller\CategoryController::edit

app_product_create:
    path: '/product/create'
    controller: App\Controller\ProductController::create

app_product_index:
    path: '/product'
    controller: App\Controller\ProductController::index