controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

app_sales:
    path: /sales
    controller: App\Controller\SalesController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_category_create:
    path: '/category/create'
    controller: App\Controller\CategoryController::create
